Version 4
SymbolType BLOCK
RECTANGLE Normal 32 48 -32 -16
PIN -32 -16 NONE 8
PINATTR PinName L-IN
PINATTR SpiceOrder 1
PIN -32 0 NONE 8
PINATTR PinName R-IN
PINATTR SpiceOrder 2
PIN -32 16 NONE 8
PINATTR PinName GND
PINATTR SpiceOrder 3
PIN -32 32 NONE 8
PINATTR PinName VCC
PINATTR SpiceOrder 4
PIN 32 -16 NONE 8
PINATTR PinName L+ OUT
PINATTR SpiceOrder 5
PIN 32 0 NONE 8
PINATTR PinName L-OUT
PINATTR SpiceOrder 6
PIN 32 16 NONE 8
PINATTR PinName R+ OUT
PINATTR SpiceOrder 7
PIN 32 32 NONE 8
PINATTR PinName R- OUT
PINATTR SpiceOrder 8
PIN -32 48 NONE 8
PINATTR PinName Audio GND
PINATTR SpiceOrder 9
